### ISSUE TITLE
Small Issue on WSL2 and Ubuntu over SSH - Render SMPL Mesh Node Fails

### ISSUE THREAD

**Issue by ProtoPompAI** [Fannovel16/ComfyUI-MotionDiff#10]
Great library. The `Render SMPL Mesh` node fails when using WSL2 or Ubuntu over SSH. Windows 11 works. The prerequisites are installed. Python used is 3.10, NVidia GPU. It appears that the offscreen rendering for pyrender is failing. Switching the PYOPENGL_PLATFORM to either 'egl' or 'osmesa' did not fix the issue. Error message is as follows when running the workflow on the readme. 

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ComfyUI/custom_nodes/ComfyUI-MotionDiff/smpl_nodes.py", line 102, in render
    color_frames, depth_frames = render_from_smpl(
  File "/home/ComfyUI/custom_nodes/ComfyUI-MotionDiff/mogen/smpl/render_mesh.py", line 259, in render_from_smpl
    r = pyrender.OffscreenRenderer(960, 960)
  File "/home/venv/lib/python3.10/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/venv/lib/python3.10/site-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/home/venv/lib/python3.10/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)
```

If someone managed to get the `Render SMPL Mesh` node to work over Ubuntu SSH or WSL2, please let me know. Thank you.

**Comment by ProtoPompAI** [comment]
It appears I had something misconfigured, it works over Ubuntu ssh

**Comment by jeolpyeoni** [comment]
Hello, can you share how you resolved this issue?
