### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by toyxyz** [Fannovel16/ComfyUI-MotionDiff#26]
I reinstalled again with the latest commit and get the following error 

!!! Exception during processing!!! [Errno 2] No such file or directory: 'C:\\Comfy\\ComfyUI_windows_portable_2\\ComfyUI\\custom_nodes\\ComfyUI-MotionDiff\\ckpts\\model_config.yaml'
Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-MotionDiff\nodes\human4d_nodes.py", line 52, in load
    model, model_cfg = load_hmr2(DEFAULT_CHECKPOINT)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-MotionDiff\motiondiff_modules\hmr2\models\__init__.py", line 76, in load_hmr2
    model_cfg = get_config(model_cfg, update_cachedir=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable_2\ComfyUI\custom_nodes\ComfyUI-MotionDiff\motiondiff_modules\hmr2\configs\__init__.py", line 104, in get_config
    cfg.merge_from_file(config_file)
  File "C:\Comfy\ComfyUI_windows_portable_2\python_embeded\Lib\site-packages\yacs\config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Comfy\\ComfyUI_windows_portable_2\\ComfyUI\\custom_nodes\\ComfyUI-MotionDiff\\ckpts\\model_config.yaml'

**Comment by JPW0080** [comment]
https://huggingface.co/spaces/brjathu/HMR2.0/tree/main/logs/train/multiruns/hmr2/0
